# Site settings
title: Roger Arendse
email: 
description: "Becoming an AI Engineer"
baseurl: ""
url: "http://rogereo.github.io"
twitter_username: arendse_roger
github_username:  rogereo
goodreads_username: rogereo
instagram_username: rogereo11
plugins:
  - jekyll-reading-time


# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

  # trigger rebuild
